import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';

const $ = (s) => document.querySelector(s);
const state = {
  mode:'garage', carId:'bmw-m3', paint:'black', wheel:'oem', bodykit:'stock', interior:'black',
  engine:'v6', drive:'awd', transmission:'dct', brakes:'steel', aero:'clean',
  ride:0, track:0, length:0, width:0, weightReduction:false, ambient:'#d9ef71', pro:false,
  lights:true, name:'BMW M3 Competition xDrive', camera:'hero'
};
let catalog = null, scene, camera, renderer, controls, carRoot, materials = {}, currentCar, baseDim = null;

const palettes = {
  sedan:{length:4.8,width:1.92,height:1.42,roof:1.52,front:0.98,rear:0.82,wheels:[-1.42,1.42],wheelZ:-0.0},
  coupe:{length:4.6,width:1.92,height:1.30,roof:1.43,front:1.04,rear:0.74,wheels:[-1.35,1.35],wheelZ:0},
  muscle:{length:5.10,width:2.0,height:1.35,roof:1.48,front:1.04,rear:0.86,wheels:[-1.58,1.58],wheelZ:0},
  suv:{length:4.95,width:2.02,height:1.72,roof:1.75,front:1.0,rear:0.93,wheels:[-1.50,1.50],wheelZ:0},
  wagon:{length:4.95,width:1.93,height:1.49,roof:1.63,front:1.0,rear:0.95,wheels:[-1.52,1.52],wheelZ:0},
  hatch:{length:4.35,width:1.88,height:1.43,roof:1.52,front:0.94,rear:0.86,wheels:[-1.28,1.28],wheelZ:0},
  gt:{length:4.75,width:1.95,height:1.31,roof:1.45,front:1.02,rear:0.82,wheels:[-1.40,1.40],wheelZ:0},
  '911':{length:4.55,width:1.90,height:1.28,roof:1.36,front:1.12,rear:0.70,wheels:[-1.30,1.30],wheelZ:0},
  supercar:{length:4.62,width:2.00,height:1.18,roof:1.29,front:1.18,rear:0.68,wheels:[-1.42,1.42],wheelZ:0},
  gtr:{length:4.72,width:1.95,height:1.34,roof:1.44,front:1.02,rear:0.83,wheels:[-1.43,1.43],wheelZ:0},
  hypercar:{length:4.72,width:2.05,height:1.12,roof:1.23,front:1.23,rear:0.65,wheels:[-1.45,1.45],wheelZ:0}
};

const q = (x) => x?.id;
function currentPaint(){return catalog.paints.find(x=>x.id===state.paint)}
function currentWheel(){return catalog.wheels.find(x=>x.id===state.wheel)}
function currentBody(){return catalog.bodykits.find(x=>x.id===state.bodykit)}
function currentEngine(){return catalog.engines.find(x=>x.id===state.engine)}
function currentDrive(){return catalog.drives.find(x=>x.id===state.drive)}
function currentTransmission(){return catalog.transmissions.find(x=>x.id===state.transmission)}
function currentBrakes(){return catalog.brakes.find(x=>x.id===state.brakes)}
function currentAero(){return catalog.aero.find(x=>x.id===state.aero)}
function currentInterior(){return catalog.interiors.find(x=>x.id===state.interior)}
function selectedCar(){return catalog.cars.find(x=>x.id===state.carId)||catalog.cars[0]}
function profile(){return palettes[selectedCar().visual]||palettes.coupe}

fetch('./data.json').then(r=>r.json()).then(d=>{catalog=d;boot()}).catch(err=>{console.error(err);useFallback()});
function useFallback(){catalog={cars:[{id:'local',brand:'DriveForge',model:'Forge Coupe',category:'Coupe',style:'custom',price:68900,hp:420,torque:520,zero:4.5,top:280,weight:1520,drive:'RWD',visual:'coupe'}],paints:[{id:'black',name:'Obsidian Black',color:'#090b0e',finish:'Metallic',cost:0,metal:.9,rough:.15}],wheels:[{id:'oem',name:'20" Performance',size:20,finish:'Satin alloy',cost:0,spokes:10}],bodykits:[{id:'stock',name:'Factory',desc:'Original body surfaces',cost:0,drop:0,width:0,downforce:0}],engines:[{id:'v6',name:'V6 Twin-Turbo',hp:510,torque:590,weight:55,zero:-.18,top:14,cost:8800}],drives:[{id:'rwd',name:'RWD',cost:0,grip:.1}],transmissions:[{id:'dct',name:'8-speed DCT',cost:0,shift:-.18}],brakes:[{id:'steel',name:'Performance Steel',cost:0,weight:0}],interiors:[{id:'black',name:'Black Leather',color:'#161719',cost:0}],aero:[{id:'clean',name:'Clean',cost:0,downforce:0}]}; boot()}

function boot(){setupLanding();setupGarage();setupStudioUI();initScene();renderGarage();renderConfig();updateAll();}
function setupLanding(){document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.start==='scratch'?'scratch':'garage';showGarage();}))}
function setupGarage(){ $('#backLanding').onclick=()=>{hide('#garage');show('#landing')}; $('#search').addEventListener('input',renderGarage); $('#brandBar').addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(!b)return;document.querySelectorAll('#brandBar [data-brand]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGarage(b.dataset.brand)}); $('#carGrid').addEventListener('click',e=>{const card=e.target.closest('[data-car]');if(!card)return;selectCar(card.dataset.car)}); }
function renderGarage(brand='ALL'){const search=($('#search').value||'').trim().toLowerCase();const brands=[...new Set(catalog.cars.map(c=>c.brand))];$('#brandBar').innerHTML='<button class="active" data-brand="ALL">ALL</button>'+brands.map(b=>`<button data-brand="${esc(b)}">${esc(b)}</button>`).join(''); if(brand!=='ALL'){document.querySelector(`#brandBar [data-brand="${CSS.escape(brand)}"]`)?.classList.add('active');document.querySelector('#brandBar [data-brand="ALL"]')?.classList.remove('active')}
const rows=catalog.cars.filter(c=>(brand==='ALL'||c.brand===brand)&&(!search||(c.brand+' '+c.model+' '+c.category).toLowerCase().includes(search))); $('#carGrid').innerHTML=rows.map(c=>`<button class="car-card ${c.id===state.carId?'selected':''}" data-car="${c.id}"><div class="thumb"></div><div class="info"><div class="brand">${esc(c.brand)}</div><div class="name">${esc(c.model)}</div><div class="meta"><span>${esc(c.category)}</span><span>${c.hp} HP · ${c.zero.toFixed(1)}s</span></div><div class="select-line"><span>${c.id===state.carId?'SELECTED':'SELECT MODEL'}</span><span>→</span></div></div></button>`).join('') || `<div style="grid-column:1/-1;padding:40px;color:#7b8791">No models matched.</div>`}
function selectCar(id){const c=catalog.cars.find(x=>x.id===id);if(!c)return;state.carId=id;state.name=c.brand+' '+c.model;showStudio();loadCarVisual(true);updateAll();toast(c.brand+' '+c.model+' selected')}
function showGarage(){hide('#landing');show('#studio');show('#garage');hide('#studio');renderGarage()}
function showStudio(){hide('#landing');hide('#garage');show('#studio');renderConfig();loadCarVisual(true);setTimeout(()=>$('#modelReference').textContent=currentCar.brand+' '+currentCar.model,0)}
function setupStudioUI(){ $('#studioGarage').onclick=()=>showGarage(); $('#studioScratch').onclick=()=>{state.mode='scratch';state.name='Forge Custom';renderConfig();updateAll();toast('Scratch architecture enabled')}; $('#resetBtn').onclick=resetBuild; $('#saveBtn').onclick=saveBuild; $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));renderConfig(b.dataset.tab)}); document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view)); $('#closePremium').onclick=()=>hide('#premiumModal'); $('#unlockPremium').onclick=()=>{state.pro=true;hide('#premiumModal');renderConfig();updateAll();toast('Pro Garage unlocked — demo only')};}
function initScene(){const host=$('#stage'); scene=new THREE.Scene(); scene.background=new THREE.Color(0x0a0d11); camera=new THREE.PerspectiveCamera(38,1,.1,100); renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; host.appendChild(renderer.domElement); const hemi=new THREE.HemisphereLight(0xe8eff4,0x0a0b0d,1.65);scene.add(hemi);const key=new THREE.DirectionalLight(0xffffff,4.7);key.position.set(6,9,10);scene.add(key);const rim=new THREE.DirectionalLight(0x9bbcf0,2.1);rim.position.set(-7,4,-5);scene.add(rim);const fill=new THREE.PointLight(0xdff09b,1.6,16);fill.position.set(0,2,3);scene.add(fill);const floor=new THREE.Mesh(new THREE.CircleGeometry(12,96),new THREE.MeshStandardMaterial({color:0x15191d,metalness:.65,roughness:.3}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;scene.add(floor);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.enablePan=false;controls.minDistance=3.2;controls.maxDistance=13;controls.target.set(0,1,0);window.addEventListener('resize',resize);resize();animate()}
function resize(){const h=$('#stage');if(!h||!renderer)return;renderer.setSize(h.clientWidth,h.clientHeight,false);camera.aspect=h.clientWidth/Math.max(1,h.clientHeight);camera.updateProjectionMatrix()}
window.addEventListener('resize',resize);
function animate(){requestAnimationFrame(animate);controls?.update();renderer?.render(scene,camera)}
function buildCar(){const p=profile();const root=new THREE.Group();const paint=currentPaint();const body=new THREE.MeshPhysicalMaterial({color:new THREE.Color(paint.color),metalness:paint.metal,roughness:paint.rough,clearcoat:.92,clearcoatRoughness:.07});const dark=new THREE.MeshPhysicalMaterial({color:0x080a0d,metalness:.72,roughness:.23,clearcoat:.35});const glass=new THREE.MeshPhysicalMaterial({color:0x0d151c,metalness:.15,roughness:.05,transparent:true,opacity:.93});const chrome=new THREE.MeshPhysicalMaterial({color:0xaab1b7,metalness:.95,roughness:.16});const rubber=new THREE.MeshStandardMaterial({color:0x050607,roughness:.9});const light=new THREE.MeshPhysicalMaterial({color:0xe9f8ff,emissive:0x9ccfff,emissiveIntensity:2.8,roughness:.12});const tail=new THREE.MeshPhysicalMaterial({color:0x8e1119,emissive:0x380006,emissiveIntensity:1.55,roughness:.16});materials={body,glass,dark,chrome,rubber,light,tail};
const add=(m,pos=[0,0,0],rot=[0,0,0])=>{m.position.set(...pos);m.rotation.set(...rot);m.castShadow=true;m.receiveShadow=true;root.add(m);return m};
const baseY=.44, L=p.length, W=p.width, H=p.height;
const bodyShape=new THREE.Shape();
bodyShape.moveTo(-L/2,.08);bodyShape.quadraticCurveTo(-L/2+.18,.30,-L*.42,.48);bodyShape.lineTo(-L*.24,.60);bodyShape.quadraticCurveTo(-L*.13,.76,L*.02,.77);bodyShape.quadraticCurveTo(L*.20,.74,L*.33,.61);bodyShape.lineTo(L*.47,.52);bodyShape.quadraticCurveTo(L/2,.42,L/2,.16);bodyShape.lineTo(L/2,-.01);bodyShape.lineTo(-L/2,-.01);bodyShape.closePath();
const geo=new THREE.ExtrudeGeometry(bodyShape,{depth:W,bevelEnabled:true,bevelSegments:4,bevelSize:.055,bevelThickness:.045,curveSegments:5});geo.rotateY(Math.PI/2);geo.translate(0,baseY,0);const bodyMesh=add(new THREE.Mesh(geo,body));
const cabShape=new THREE.Shape();cabShape.moveTo(-L*.23,.74);cabShape.quadraticCurveTo(-L*.13,H*.92,0,H*.93);cabShape.quadraticCurveTo(L*.16,H*.92,L*.28,.70);cabShape.lineTo(L*.22,.61);cabShape.lineTo(-L*.20,.62);cabShape.closePath();const cabGeo=new THREE.ExtrudeGeometry(cabShape,{depth:W*.80,bevelEnabled:true,bevelSegments:3,bevelSize:.035,bevelThickness:.03});cabGeo.rotateY(Math.PI/2);cabGeo.translate(0,baseY,0);add(new THREE.Mesh(cabGeo,body));
const windowGeo=new THREE.ExtrudeGeometry(cabShape,{depth:W*.81,bevelEnabled:true,bevelSegments:2,bevelSize:.018,bevelThickness:.018});windowGeo.rotateY(Math.PI/2);windowGeo.translate(0,baseY+.005,0);const win=add(new THREE.Mesh(windowGeo,glass));win.scale.set(.92,.82,.96);win.position.y=.04;
add(new THREE.Mesh(new THREE.BoxGeometry(W*.98,.09,.32),dark),[0,baseY+.18,L/2-.02]);add(new THREE.Mesh(new THREE.BoxGeometry(W*.95,.08,.28),dark),[0,baseY+.16,-L/2+.03]);
const bumperF=add(new THREE.Mesh(new THREE.BoxGeometry(W*.92,.18,.20),dark),[0,baseY+.15,L/2+.06]);const bumperR=add(new THREE.Mesh(new THREE.BoxGeometry(W*.88,.17,.18),dark),[0,baseY+.13,-L/2-.05]);
add(new THREE.Mesh(new THREE.BoxGeometry(W*.72,.045,.07),light),[0,baseY+.42,L/2+.055]);add(new THREE.Mesh(new THREE.BoxGeometry(W*.72,.04,.07),tail),[0,baseY+.38,-L/2-.055]);
const wheel=currentWheel();const wheelR=.34 + (wheel.size-20)*.012; for(const z of p.wheels){for(const x of[-W*.53,W*.53]){const tire=add(new THREE.Mesh(new THREE.CylinderGeometry(wheelR,wheelR,.16,40),rubber),[x,baseY+.17,z],[0,0,Math.PI/2]);const rim=add(new THREE.Mesh(new THREE.CylinderGeometry(wheelR*.67,wheelR*.67,.17,32),chrome),[x,baseY+.17,z],[0,0,Math.PI/2]);for(let i=0;i<wheel.spokes;i++){const sp=add(new THREE.Mesh(new THREE.BoxGeometry(.028,wheelR*.60,.08),dark),[x+(x>0?.0:0),baseY+.17,z],[Math.PI/2,0,(Math.PI*2*i/wheel.spokes)]);sp.scale.x=.75}}}
// Mirrors
for(const x of[-W*.54,W*.54])add(new THREE.Mesh(new THREE.BoxGeometry(.12,.07,.18),dark),[x,baseY+.56,-.05],[0,.15,0]);
if(p===palettes.suv||currentCar.visual==='suv'){add(new THREE.Mesh(new THREE.BoxGeometry(W*.62,.05,.11),dark),[0,baseY+H*.70,-L*.24])}
root.userData={p};return root}
function loadCarVisual(){if(!scene)return;const c=selectedCar();currentCar=c;$('#viewerStatus').textContent='UPDATING';const newRoot=buildCar();if(carRoot)scene.remove(carRoot);carRoot=newRoot;scene.add(carRoot);fitCar();applyVisualState();$('#viewerStatus').textContent='READY';}
function fitCar(){const box=new THREE.Box3().setFromObject(carRoot);const size=box.getSize(new THREE.Vector3());const max=Math.max(size.x,size.y,size.z);const s=4.6/max;baseDim={scale:s};carRoot.scale.setScalar(s);const center=box.getCenter(new THREE.Vector3());carRoot.position.set(-center.x*s,-box.min.y*s, -center.z*s);controls.target.set(0,.9,0);setView(state.camera,true)}
function applyVisualState(){if(!carRoot)return;const paint=currentPaint();materials.body.color.set(paint.color);materials.body.metalness=paint.metal;materials.body.roughness=paint.rough;const b=currentBody();const w=currentWheel();const p=profile();const sx=1+(state.width+b.width*.08)/100;const sz=1+(state.length)/100;const sy=1+(b.drop+state.ride)/500;carRoot.scale.setScalar(baseDim.scale);carRoot.scale.x*=sx;carRoot.scale.y*=sy;carRoot.scale.z*=sz;carRoot.position.y=(b.drop+state.ride)*.008; // aero overlays
  carRoot.children.filter(x=>x.userData.dfExtra).forEach(x=>carRoot.remove(x));
  const aeroMat= new THREE.MeshPhysicalMaterial({color:0x101316,metalness:.78,roughness:.24,clearcoat:.5});
  const L=p.length,W=p.width,H=p.height; const addExtra=(geo,pos,rot=[0,0,0])=>{const m=new THREE.Mesh(geo,aeroMat);m.position.set(...pos);m.rotation.set(...rot);m.userData.dfExtra=true;carRoot.add(m)};
  if(state.bodykit!=='stock'){addExtra(new THREE.BoxGeometry(W*.82,.045,.40),[0,.26,L/2+.08],[0,0,0]);for(const x of[-W*.52,W*.52])addExtra(new THREE.BoxGeometry(.07,.09,L*.42),[x,.31,0])}
  if(['wide','track'].includes(state.bodykit)){for(const x of[-W*.55,W*.55])addExtra(new THREE.BoxGeometry(.08,.19,L*.38),[x,.48,0])}
  if(['track','luxury'].includes(state.bodykit)||currentAero().downforce>0){addExtra(new THREE.BoxGeometry(W*.65,.055,.16),[0,H*.74,-L*.46]);}
  if(currentAero().downforce>80){addExtra(new THREE.BoxGeometry(W*.58,.05,.12),[0,H*.82,-L*.43]);}
  if(!state.lights){materials.light.emissiveIntensity=0;materials.tail.emissiveIntensity=0}else{materials.light.emissiveIntensity=2.8;materials.tail.emissiveIntensity=1.55}
}
function setView(mode,snap=false){state.camera=mode;const poses={hero:[6.8,3.1,7.4],front:[0,2.5,9.6],side:[9.4,2.6,0],rear:[0,2.4,-9.2],interior:[0,1.35,.45]};const p=poses[mode]||poses.hero;camera.position.set(...p);controls.target.set(0,mode==='interior'?1.28:.9,mode==='interior'?.6:0);controls.maxDistance=mode==='interior'?3.5:13;controls.minDistance=mode==='interior'?.35:3.0;controls.update();document.querySelectorAll('.view-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===mode))}
function tabTitle(title,sub){return `<div class="config-section"><h3>${title}</h3><p>${sub||''}</p>`}
function choice(item,current){const locked=item.premium&&!state.pro;return `<button class="choice ${item.id===current?'active':''} ${locked?'locked':''}" data-id="${item.id}" data-locked="${locked}"><strong>${esc(item.name)}</strong><small>${item.finish||item.desc||item.layout||''}</small><span class="price-tag">${locked?'LOCKED':item.cost?'+$'+item.cost.toLocaleString():'INCLUDED'}</span>${locked?'<span class="pro-corner">PRO</span>':''}</button>`}
function renderConfig(tab='model'){if(!catalog)return;const c=selectedCar();const t=tab||'model';let html=''; if(t==='model'){html=tabTitle('Selected model','Real-world reference profile with an original DriveForge visual body');html+=`<div class="spec-table"><div class="spec-row"><span>Model</span><b>${esc(c.brand+' '+c.model)}</b></div><div class="spec-row"><span>Category</span><b>${esc(c.category)}</b></div><div class="spec-row"><span>Base power</span><b>${c.hp} HP</b></div><div class="spec-row"><span>Base drivetrain</span><b>${c.drive}</b></div><div class="spec-row"><span>Reference value</span><b>$${c.price.toLocaleString()}</b></div></div>`;html+='</div>'; if(state.mode==='scratch'){html+=tabTitle('Custom architecture','Adjust the silhouette without losing the selected vehicle class');html+=slider('length','Length',state.length,-8,10,'%')+slider('width','Width',state.width,-6,10,'%');html+='</div>'} html+=tabTitle('Build name','');html+=`<input id="nameInput" value="${esc(state.name)}" maxlength="34" style="width:100%;padding:11px 12px;border:1px solid #2a333d;background:#0f1419;color:#fff;border-radius:9px">`;html+='</div>';
} else if(t==='exterior'){html=tabTitle('Paint','Live PBR body material');html+='<div class="swatches">'+catalog.paints.map(p=>`<button class="swatch ${state.paint===p.id?'active':''}" data-paint="${p.id}" style="background:${p.color}" title="${esc(p.name)}"></button>`).join('')+'</div></div>';html+=tabTitle('Body kit','Physical aero and stance changes');html+='<div class="choice-grid">'+catalog.bodykits.map(x=>choice(x,state.bodykit)).join('')+'</div></div>';html+=tabTitle('Lighting','Signature lighting');html+=toggle('lights','LED signature lighting','Headlight and tail-light emissive materials',state.lights);html+=toggle('exhaust','Visible exhaust hardware','Show performance tips in the build',state.exhaust??true)}
else if(t==='wheels'){html=tabTitle('Wheel design','Wheel diameter changes the 3D wheel proportions');html+='<div class="choice-grid">'+catalog.wheels.map(x=>choice(x,state.wheel)).join('')+'</div></div>';html+=tabTitle('Brake hardware','Brake mass affects the live weight model');html+='<div class="choice-grid">'+catalog.brakes.map(x=>choice(x,state.brakes)).join('')+'</div></div>';html+=tabTitle('Stance','Live ride-height and track changes');html+=slider('ride','Ride height',state.ride,-25,20,' mm')+slider('track','Track width',state.track,-10,24,' mm')+'</div>'}
else if(t==='interior'){html=tabTitle('Material package','Cabin materials change the interior color treatment');html+='<div class="choice-grid">'+catalog.interiors.map(x=>choice(x,state.interior)).join('')+'</div></div>';html+=tabTitle('Ambient lighting','Choose the cabin accent');html+='<div class="swatches">'+['#d9ef71','#9abcff','#ff7b82','#d9c28b','#ffffff'].map(c2=>`<button class="swatch ${state.ambient===c2?'active':''}" data-ambient="${c2}" style="background:${c2}"></button>`).join('')+'</div></div>'}
else if(t==='power'){html=tabTitle('Engine','Formula-based performance model');html+='<div class="choice-grid">'+catalog.engines.map(x=>choice(x,state.engine)).join('')+'</div></div>';html+=tabTitle('Drivetrain','Traction changes acceleration');html+='<div class="choice-grid">'+catalog.drives.map(x=>choice(x,state.drive)).join('')+'</div></div>';html+=tabTitle('Transmission','Shift strategy changes acceleration estimate');html+='<div class="choice-grid">'+catalog.transmissions.map(x=>choice(x,state.transmission)).join('')+'</div></div>'}
else if(t==='chassis'){html=tabTitle('Aerodynamics','Downforce and stance influence the performance model');html+='<div class="choice-grid">'+catalog.aero.map(x=>choice(x,state.aero)).join('')+'</div></div>';html+=tabTitle('Weight reduction','Remove non-structural mass');html+=toggle('weightReduction','Lightweight package','Reduces simulated vehicle mass by 6%',state.weightReduction);html+='</div>'}
else if(t==='summary'){const p=performance();html=tabTitle('Final specification','A snapshot of the active configuration');html+=`<div class="spec-table"><div class="spec-row"><span>Build</span><b>${esc(state.name)}</b></div><div class="spec-row"><span>Paint</span><b>${esc(currentPaint().name)}</b></div><div class="spec-row"><span>Wheels</span><b>${esc(currentWheel().name)}</b></div><div class="spec-row"><span>Body kit</span><b>${esc(currentBody().name)}</b></div><div class="spec-row"><span>Engine</span><b>${esc(currentEngine().name)}</b></div><div class="spec-row"><span>Drivetrain</span><b>${esc(currentDrive().name)}</b></div><div class="spec-row"><span>Performance</span><b>${p.hp} HP · ${p.zero.toFixed(1)} s</b></div><div class="spec-row"><span>Build value</span><b>$${p.price.toLocaleString()}</b></div></div></div>`;html+=`<div class="premium-box"><div class="mini">DRIVEFORGE PRO</div><h4>${state.pro?'PRO GARAGE UNLOCKED':'Unlock more of the build'}</h4><p>${state.pro?'Premium hardware is active on this build.':'V10/V12/hybrid engines, forged carbon wheels, widebody and track programs, carbon interiors and advanced aero.'}</p><button id="summaryPro" class="solid-btn">${state.pro?'PRO ACTIVE':'UNLOCK FOR $20'}</button></div>`}
$('#config').innerHTML=html;bindConfig();}
function toggle(id,title,sub,on){return `<div class="toggle-row"><div class="toggle-copy"><b>${title}</b><small>${sub}</small></div><button class="switch ${on?'on':''}" id="${id}Switch"><i></i></button></div>`}
function slider(id,label,val,min,max,suffix){return `<div class="slider-row"><label>${label}</label><span class="value" id="${id}Value">${val>0?'+':''}${val}${suffix}</span></div><input class="range" id="${id}Range" type="range" min="${min}" max="${max}" value="${val}">`}
function bindConfig(){const area=$('#config');area.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(b.dataset.locked==='true'||b.dataset.locked==='true'){show('#premiumModal');return}const id=b.dataset.id;const tab=document.querySelector('#tabs button.active')?.dataset.tab;const map={exterior:['bodykits','bodykit'],wheels:['wheels','wheel'],power:['engines','engine']};if(tab==='exterior'&&catalog.bodykits.some(x=>x.id===id))state.bodykit=id;else if(tab==='wheels'&&catalog.wheels.some(x=>x.id===id))state.wheel=id;else if(tab==='wheels'&&catalog.brakes.some(x=>x.id===id))state.brakes=id;else if(tab==='power'&&catalog.engines.some(x=>x.id===id))state.engine=id;else if(tab==='power'&&catalog.drives.some(x=>x.id===id))state.drive=id;else if(tab==='power'&&catalog.transmissions.some(x=>x.id===id))state.transmission=id;else if(tab==='interior')state.interior=id;else if(tab==='chassis')state.aero=id;applyVisualState();renderConfig(tab);updateAll();});
area.querySelectorAll('[data-paint]').forEach(b=>b.onclick=()=>{state.paint=b.dataset.paint;applyVisualState();renderConfig('exterior');updateAll();});area.querySelectorAll('[data-ambient]').forEach(b=>b.onclick=()=>{state.ambient=b.dataset.ambient;renderConfig('interior')});const sliders=['ride','track','length','width'];for(const id of sliders){const r=$('#'+id+'Range');if(r)r.oninput=()=>{state[id]=+r.value;$('#'+id+'Value').textContent=(state[id]>0?'+':'')+state[id]+(id==='ride'||id==='track'?' mm':'%');applyVisualState();updateAll()}}const name=$('#nameInput');if(name)name.oninput=()=>{state.name=name.value||'Untitled Forge';$('#buildTitle').textContent=state.name;$('#viewerName').textContent=state.name};for(const id of ['lights','weightReduction']){const sw=$('#'+id+'Switch');if(sw)sw.onclick=()=>{state[id]=!state[id];sw.classList.toggle('on',state[id]);applyVisualState();updateAll()}}$('#summaryPro')?.addEventListener('click',()=>state.pro?null:show('#premiumModal'));}
function performance(){const c=selectedCar(),e=currentEngine(),d=currentDrive(),t=currentTransmission(),b=currentBody(),br=currentBrakes(),a=currentAero();let hp=Math.round(c.hp*.35+e.hp*.65+a.downforce*.06);let tq=Math.round(c.torque*.38+e.torque*.62);let wt=Math.max(1050,Math.round(c.weight+e.weight+br.weight+(currentWheel().size-20)*3-(state.weightReduction?95:0)));let zero=Math.max(2.1,c.zero+(e.zero*.7)+t.shift-d.grip*.45+(state.ride<0?-0.06:0)-a.downforce*.0015-(b.drop<0?.08:0));let top=Math.min(390,Math.round(c.top+e.top+d.grip*4+(b.drop<0?4:0)));let price=c.price+currentPaint().cost+currentWheel().cost+b.cost+e.cost+d.cost+t.cost+br.cost+a.cost+currentInterior().cost+(state.weightReduction?3200:0);return{hp,tq,torque:tq,wt,zero,top,price,pwr:Math.round(hp/(wt/1000))}}
function updateAll(){const c=selectedCar(),p=performance();$('#hp').textContent=p.hp;$('#torque').textContent=p.torque;$('#zero').textContent=p.zero.toFixed(1);$('#top').textContent=p.top;$('#weight').textContent=p.wt.toLocaleString();$('#priceLarge').textContent='$'+p.price.toLocaleString();$('#buildTitle').textContent=state.name;$('#viewerName').textContent=state.name;$('#viewerSub').textContent=`${c.brand} ${c.model} · ${c.category} · original DriveForge 3D reference body`;$('#proPill').textContent=state.pro?'PRO':'FREE';$('#proPill').classList.toggle('on',state.pro);$('#studioGarage').classList.toggle('active',state.mode!=='scratch');$('#studioScratch').classList.toggle('active',state.mode==='scratch')}
function resetBuild(){Object.assign(state,{paint:'black',wheel:'oem',bodykit:'stock',interior:'black',engine:'v6',drive:'awd',transmission:'dct',brakes:'steel',aero:'clean',ride:0,track:0,length:0,width:0,weightReduction:false,pro:state.pro,name:selectedCar().brand+' '+selectedCar().model});renderConfig(document.querySelector('#tabs button.active')?.dataset.tab||'model');applyVisualState();updateAll();toast('Build reset')}
function saveBuild(){const p=performance();const build={name:state.name,model:selectedCar(),paint:state.paint,wheel:state.wheel,bodykit:state.bodykit,interior:state.interior,engine:state.engine,drive:state.drive,transmission:state.transmission,brakes:state.brakes,aero:state.aero,ride:state.ride,track:state.track,length:state.length,width:state.width,weightReduction:state.weightReduction,pro:state.pro,performance:p};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(build,null,2)],{type:'application/json'}));a.download=(state.name||'driveforge-build').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json';a.click();URL.revokeObjectURL(a.href);toast('Specification saved')}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(sel){$(sel).classList.remove('hidden')}function hide(sel){$(sel).classList.add('hidden')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
renderGarage();
