
const cars=[
{id:'bmw-m3',brand:'BMW',name:'M3 Competition xDrive',year:2026,category:'Sedan',tag:'High-performance sport sedan',hp:523,torque:650,zero:3.4,top:290,price:88600,type:'sedan',color:'#3d4650'},
{id:'bmw-m4',brand:'BMW',name:'M4 Competition xDrive',year:2026,category:'Coupe',tag:'High-performance coupe',hp:523,torque:650,zero:3.4,top:290,price:91500,type:'coupe',color:'#1d3550'},
{id:'bmw-x5m',brand:'BMW',name:'X5 M Competition',year:2026,category:'SUV',tag:'Performance SUV',hp:617,torque:750,zero:3.7,top:285,price:131000,type:'suv',color:'#25292f'},
{id:'dodge-charger',brand:'Dodge',name:'Charger Scat Pack',year:2026,category:'Muscle Sedan',tag:'High-output twin-turbo muscle',hp:550,torque:720,zero:3.9,top:280,price:54995,type:'muscle',color:'#191b1f'},
{id:'ford-mustang',brand:'Ford',name:'Mustang GT',year:2026,category:'Muscle Coupe',tag:'5.0 V8 fastback',hp:486,torque:567,zero:4.0,top:250,price:51080,type:'coupe',color:'#314a6a'},
{id:'toyota-supra',brand:'Toyota',name:'GR Supra 3.0',year:2026,category:'Sports Coupe',tag:'Turbo straight-six',hp:382,torque:499,zero:3.9,top:250,price:56900,type:'coupe',color:'#a40f18'},
{id:'porsche-911',brand:'Porsche',name:'911 Carrera',year:2026,category:'Sports Coupe',tag:'Rear-engine sports car',hp:388,torque:450,zero:4.1,top:294,price:135500,type:'super',color:'#b7b9bd'},
{id:'corvette',brand:'Chevrolet',name:'Corvette Stingray',year:2026,category:'Supercar',tag:'Mid-engine V8',hp:495,torque:637,zero:2.9,top:312,price:70000,type:'super',color:'#8e171b'},
{id:'gtr',brand:'Nissan',name:'GT-R',year:2024,category:'Supercar',tag:'Twin-turbo AWD icon',hp:565,torque:633,zero:2.9,top:315,price:121000,type:'super',color:'#526d87'},
{id:'amg-gt',brand:'Mercedes-AMG',name:'GT 63',year:2026,category:'Grand Touring',tag:'Luxury performance coupe',hp:577,torque:800,zero:3.2,top:315,price:188000,type:'coupe',color:'#4a4a4c'},
{id:'audi-rs6',brand:'Audi',name:'RS 6 Avant Performance',year:2026,category:'Wagon',tag:'High-performance estate',hp:621,torque:850,zero:3.4,top:305,price:130000,type:'wagon',color:'#2d333b'},
{id:'honda-type-r',brand:'Honda',name:'Civic Type R',year:2026,category:'Hatchback',tag:'Front-drive performance hatch',hp:315,torque:420,zero:5.4,top:275,price:46000,type:'hatch',color:'#e7e7e7'},
{id:'subaru-wrx',brand:'Subaru',name:'WRX tS',year:2026,category:'Sedan',tag:'AWD turbo sport sedan',hp:271,torque:350,zero:5.7,top:240,price:48000,type:'sedan',color:'#0d4070'},
{id:'lexus-lc500',brand:'Lexus',name:'LC 500',year:2026,category:'Coupe',tag:'Naturally aspirated V8 GT',hp:471,torque:540,zero:4.7,top:270,price:102000,type:'coupe',color:'#bfc3c8'},
{id:'mclaren-artura',brand:'McLaren',name:'Artura',year:2026,category:'Supercar',tag:'Twin-turbo V6 hybrid',hp:690,torque:720,zero:3.0,top:330,price:240000,type:'super',color:'#8d8f97'},
{id:'aston-vantage',brand:'Aston Martin',name:'Vantage',year:2026,category:'Sports Coupe',tag:'Twin-turbo V8 GT',hp:656,torque:800,zero:3.4,top:325,price:191000,type:'coupe',color:'#1b4639'},
{id:'lamborghini-revuelto',brand:'Lamborghini',name:'Revuelto',year:2026,category:'Hypercar',tag:'V12 plug-in hybrid',hp:1001,torque:725,zero:2.5,top:350,price:608000,type:'super',color:'#d5a300'},
{id:'ferrari-296',brand:'Ferrari',name:'296 GTB',year:2026,category:'Supercar',tag:'V6 plug-in hybrid',hp:819,torque:740,zero:2.9,top:330,price:347000,type:'super',color:'#8b1020'},
{id:'porsche-turbos',brand:'Porsche',name:'911 Turbo S',year:2026,category:'Supercar',tag:'Flagship hybrid',hp:711,torque:800,zero:2.5,top:322,price:192000,type:'super',color:'#d0d2d4'},
{id:'dodge-daytona',brand:'Dodge',name:'Charger Daytona Scat Pack',year:2026,category:'Muscle EV',tag:'Electric performance muscle',hp:670,torque:850,zero:3.3,top:216,price:59995,type:'muscle',color:'#d7d8da'},
{id:'toyota-gr86',brand:'Toyota',name:'GR86',year:2026,category:'Sports Coupe',tag:'Lightweight boxer sports car',hp:228,torque:250,zero:6.1,top:226,price:30000,type:'coupe',color:'#566d89'},
{id:'ford-raptor',brand:'Ford',name:'F-150 Raptor',year:2026,category:'Pickup',tag:'High-speed off-road truck',hp:450,torque:691,zero:5.6,top:180,price:79000,type:'pickup',color:'#2e3135'},
{id:'chevy-tahoe',brand:'Chevrolet',name:'Tahoe RST',year:2026,category:'SUV',tag:'Full-size performance SUV',hp:420,torque:624,zero:5.9,top:210,price:72000,type:'suv',color:'#23262a'},
{id:'mercedes-amg-g63',brand:'Mercedes-AMG',name:'G 63',year:2026,category:'SUV',tag:'Luxury off-road icon',hp:577,torque:850,zero:4.5,top:240,price:190000,type:'suv',color:'#202226'}
];
const photoMap={
  'bmw-m3':'assets/car-bmw-m3.jpg',
  'bmw-m4':'assets/car-bmw-m3.jpg',
  'bmw-x5m':'assets/car-bmw-m3.jpg',
  'dodge-charger':'assets/car-dodge-charger.jpg',
  'dodge-daytona':'assets/car-dodge-charger.jpg',
  'ford-mustang':'assets/car-ford-mustang.jpg',
  'ford-raptor':'assets/car-ford-mustang.jpg',
  'toyota-supra':'assets/car-toyota-supra.jpg',
  'toyota-gr86':'assets/car-toyota-supra.jpg',
  'porsche-911':'assets/car-porsche-911.jpg',
  'porsche-turbos':'assets/car-porsche-911.jpg',
  'corvette':'assets/car-corvette.jpg',
  'gtr':'assets/car-gtr.jpg',
  'amg-gt':'assets/car-amg-gt.jpg',
  'mercedes-amg-g63':'assets/car-amg-gt.jpg',
  'audi-rs6':'assets/car-audi-rs6.jpg',
  'lexus-lc500':'assets/car-lexus-lc500.jpg',
  'honda-type-r':'assets/car-honda-type-r.jpg',
  'subaru-wrx':'assets/car-subaru-wrx.jpg',
  'mclaren-artura':'assets/car-porsche-911.jpg',
  'aston-vantage':'assets/car-porsche-911.jpg',
  'lamborghini-revuelto':'assets/car-corvette.jpg',
  'ferrari-296':'assets/car-corvette.jpg',
  'chevy-tahoe':'assets/car-corvette.jpg'
};
function carPhoto(c){return photoMap[c.id]||'assets/car-bmw-m3.jpg'}
const brands=['ALL',...new Set(cars.map(c=>c.brand))];
const state={car:'bmw-m3',brand:'ALL',search:'',tab:'vehicle',paint:'#3d4650',finish:'metallic',wheel:'stock',body:'stock',engine:'stock',drive:'awd',interior:'black',pro:false,ride:0,track:0,customHp:523};
const paints=[['#101214','Obsidian','Metallic',0],['#c7c9cc','Silver','Metallic',650],['#8f121c','Crimson','Pearl',950],['#173d6d','Deep Blue','Metallic',950],['#d4d3ce','Chalk','Gloss',350],['#28302d','Stealth Green','Satin',1250],['#4a4e54','Graphite','Matte',1600]];
const wheels=[['stock','20” Sport','Included',0],['mesh','21” Mesh','Gunmetal',1800],['forged','22” Forged','Brushed',4800],['carbon','22” Carbon','Carbon',6200]];
const bodies=[['stock','Stock','Factory form',0],['sport','Sport','Subtle aero',1800],['wide','Widebody','Fender flares',7200,true],['track','Track','Splitter + wing',8900,true],['luxury','Luxury','Comfort aero',6500,true]];
const engines=[['stock','Factory','Keep selected profile',0],['i6','I6 Turbo','+90 HP',6200],['v8','V8 Twin-Turbo','+167 HP',14500],['v10','V10 N/A','+257 HP',21000,true],['v12','V12 Twin-Turbo','+377 HP',32000,true],['ev','Dual Motor EV','+110 HP',12000]];
function $(s){return document.querySelector(s)}
function car(){return cars.find(c=>c.id===state.car)||cars[0]}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window.toastT);window.toastT=setTimeout(()=>el.classList.add('hidden'),2200)}
function renderBrands(){const row=$('#brandRow');row.innerHTML=brands.map(b=>`<button class="brand ${state.brand===b?'active':''}" data-brand="${b}">${b}</button>`).join('')}
function filteredCars(){const q=state.search.toLowerCase();return cars.filter(c=>(state.brand==='ALL'||c.brand===state.brand)&&(!q||(c.brand+' '+c.name+' '+c.category).toLowerCase().includes(q)))}
function art(c){return `<div class="car-art"><img class="car-photo" loading="lazy" src="${carPhoto(c)}" alt="${c.brand} ${c.name}"><span class="car-photo-shade"></span></div>`}
function renderGarage(){const grid=$('#garageGrid');grid.innerHTML=filteredCars().map(c=>`<button type="button" class="car-card ${state.car===c.id?'selected':''}" data-car="${c.id}" aria-pressed="${state.car===c.id}">${art(c)}<div class="car-info"><span class="brand-name">${c.brand}</span><h3>${c.name}</h3><span class="meta">${c.year} · ${c.category}</span><div class="row"><span class="price">$${c.price.toLocaleString()}</span><span class="select-mark">${state.car===c.id?'SELECTED ✓':'SELECT MODEL →'}</span></div></div></button>`).join('')||'<div class="notice">No vehicles match that search.</div>'}
function showHome(){document.querySelector('#homeView').classList.remove('hidden');document.querySelector('#studioView').classList.add('hidden')}
function showStudio(){document.querySelector('#homeView').classList.add('hidden');document.querySelector('#studioView').classList.remove('hidden');renderPanel();renderScene()}
function optionHtml(arr,current,kind){return arr.map(o=>{const locked=o[4]&&!state.pro;return `<button class="option ${current===o[0]?'active':''}" data-kind="${kind}" data-id="${o[0]}" ${locked?'data-locked="1"':''}><strong>${o[1]}</strong><small>${o[2]} · ${o[3]?'$'+o[3].toLocaleString():'Included'}</small>${locked?'<span class="pro-pill">PRO</span>':''}</button>`}).join('')}
function renderPanel(){const c=car();let h='';if(state.tab==='vehicle'){h=`<div class="panel-section"><h4>Garage selection</h4><div class="notice">Select a vehicle. The preview, specifications, price and build state change immediately.</div><div class="vehicle-option-grid">${cars.map(x=>`<button type="button" class="vehicle-option ${state.car===x.id?'active':''}" data-kind="car" data-id="${x.id}" aria-pressed="${state.car===x.id}"><img loading="lazy" src="${carPhoto(x)}" alt="${x.brand} ${x.name}"><span><b>${x.brand}</b><strong>${x.name}</strong><small>${x.category} · $${x.price.toLocaleString()}</small></span>${state.car===x.id?'<em>✓</em>':''}</button>`).join('')}</div></div>`;}
if(state.tab==='paint'){h=`<div class="panel-section"><h4>Paint</h4><div class="swatches">${paints.map(p=>`<button class="swatch ${state.paint===p[0]?'active':''}" data-kind="paint" data-id="${p[0]}" style="background:${p[0]}" title="${p[1]}"></button>`).join('')}</div><div class="notice" style="margin-top:12px">${paints.find(p=>p[0]===state.paint)[1]} · ${paints.find(p=>p[0]===state.paint)[2]}</div></div><div class="panel-section"><h4>Finish</h4><div class="option-grid">${[['metallic','Metallic','Reflective clearcoat',0],['matte','Matte','Low-reflection surface',1600],['satin','Satin','Soft sheen',1250],['gloss','Gloss','High gloss',350]].map(o=>`<button class="option ${state.finish===o[0]?'active':''}" data-kind="finish" data-id="${o[0]}"><strong>${o[1]}</strong><small>${o[2]} · ${o[3]?'$'+o[3]:'Included'}</small></button>`).join('')}</div></div>`}
if(state.tab==='wheels'){h=`<div class="panel-section"><h4>Wheel design</h4><div class="option-grid">${optionHtml(wheels,state.wheel,'wheel')}</div></div><div class="panel-section"><h4>Stance</h4>${slider('ride','Ride height',state.ride,-25,15,' mm')}${slider('track','Track width',state.track,-8,22,' mm')}</div>`}
if(state.tab==='body'){h=`<div class="panel-section"><h4>Body program</h4><div class="option-grid">${optionHtml(bodies,state.body,'body')}</div></div><div class="panel-section"><h4>Aerodynamics</h4><div class="option-grid">${[['clean','Clean','Road-focused aero',0],['active','Active','Adaptive aero',4500],['race','Race','High-downforce aero',9800,true]].map(o=>`<button class="option ${state.aero===o[0]?'active':''}" data-kind="aero" data-id="${o[0]}" ${o[4]&&!state.pro?'data-locked="1"':''}><strong>${o[1]}</strong><small>${o[2]} · ${o[3]?'$'+o[3].toLocaleString():'Included'}</small>${o[4]&&!state.pro?'<span class="pro-pill">PRO</span>':''}</button>`).join('')}</div></div>`}
if(state.tab==='power'){const e=engines.find(x=>x[0]===state.engine);h=`<div class="panel-section"><h4>Engine</h4><div class="option-grid">${optionHtml(engines,state.engine,'engine')}</div></div><div class="panel-section"><h4>Drivetrain</h4><div class="option-grid">${[['fwd','FWD','Front drive',0],['rwd','RWD','Rear drive',1200],['awd','AWD','All wheel drive',3200]].map(o=>`<button class="option ${state.drive===o[0]?'active':''}" data-kind="drive" data-id="${o[0]}"><strong>${o[1]}</strong><small>${o[2]} · ${o[3]?'$'+o[3].toLocaleString():'Included'}</small></button>`).join('')}</div></div><div class="panel-section"><h4>Power tuning</h4>${slider('tune','Power target',0,0,120,' %')}</div>`}
if(state.tab==='interior'){h=`<div class="panel-section"><h4>Interior theme</h4><div class="option-grid">${[['black','Black Leather','Technical',0],['tan','Saddle Leather','Warm',1200],['red','Burgundy','Sport',1500],['alcantara','Alcantara + Leather','Track',2100],['carbon','Carbon + Alcantara','Premium',3900,true]].map(o=>`<button class="option ${state.interior===o[0]?'active':''}" data-kind="interior" data-id="${o[0]}" ${o[4]&&!state.pro?'data-locked="1"':''}><strong>${o[1]}</strong><small>${o[2]} · ${o[3]?'$'+o[3].toLocaleString():'Included'}</small>${o[4]&&!state.pro?'<span class="pro-pill">PRO</span>':''}</button>`).join('')}</div></div>`}
$('#panelBody').innerHTML=h}
function slider(id,label,val,min,max,suffix){return `<div class="range-row"><span>${label}</span><b id="${id}Value">${val>0?'+':''}${val}${suffix}</b></div><input class="range" id="${id}Range" type="range" min="${min}" max="${max}" value="${val}">`}
function renderScene(){const c=car();const v=$('#viewerCar');v.className='viewer-car '+c.type+' '+state.body;v.style.setProperty('--photo',`url('${carPhoto(c)}')`);v.style.setProperty('--paint',state.paint);v.setAttribute('aria-label',c.brand+' '+c.name+' preview');$('#viewerName').textContent=c.brand+' '+c.name;$('#viewerMeta').textContent=c.year+' · '+c.category+' · '+state.drive.toUpperCase();$('#buildTitle').textContent=c.brand+' '+c.name;$('#buildSubtitle').textContent=c.tag+' · DriveForge visualization';updateStats()}
function updateStats(){const c=car();const eng=engines.find(e=>e[0]===state.engine)||engines[0];let hp=c.hp,zero=c.zero,top=c.top,price=c.price; if(state.engine!=='stock'){const delta=Number(eng[2].match(/\+([0-9]+)/)?.[1]||0);hp+=delta;zero=Math.max(2.2,zero-delta*.003);top=Math.min(380,top+delta*.035);price+=eng[3]}price+=paints.find(p=>p[0]===state.paint)?.[3]||0;price+=wheels.find(w=>w[0]===state.wheel)?.[3]||0;price+=bodies.find(b=>b[0]===state.body)?.[3]||0; if(state.ride<0)zero-=.05; if(state.track>0)zero-=.03;$('#statHp').textContent=Math.round(hp);$('#statZero').textContent=Math.max(2.2,zero).toFixed(1);$('#statTop').textContent=Math.round(top);$('#buildPrice').textContent='$'+Math.round(price).toLocaleString()}
$('#garageGrid').addEventListener('click',e=>{const card=e.target.closest('[data-car]');if(!card)return;e.preventDefault();state.car=card.dataset.car;const c=car();state.paint=c.color;state.engine='stock';state.body='stock';renderGarage();showStudio();renderPanel();renderScene();toast(c.brand+' '+c.name+' selected')});
$('#brandRow').addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(!b)return;state.brand=b.dataset.brand;renderBrands();renderGarage()});
$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;renderGarage()});
$('#panelTabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;state.tab=b.dataset.tab;document.querySelectorAll('#panelTabs button').forEach(x=>x.classList.toggle('active',x===b));renderPanel()});
$('#panelBody').addEventListener('click',e=>{const b=e.target.closest('.option,.swatch');if(!b)return;if(b.dataset.locked){$('#premiumModal').classList.remove('hidden');return}const k=b.dataset.kind,id=b.dataset.id;if(k==='car'){state.car=id;state.paint=car().color;state.engine='stock';state.body='stock';renderGarage();renderScene();renderPanel();toast(car().brand+' '+car().name+' selected')}else if(k==='paint'){state.paint=id;renderScene();renderPanel()}else if(k==='finish'){state.finish=id;renderPanel()}else if(k==='wheel'){state.wheel=id;renderScene();renderPanel()}else if(k==='body'){state.body=id;renderScene();renderPanel()}else if(k==='aero'){state.aero=id;renderPanel()}else if(k==='engine'){state.engine=id;renderScene();renderPanel()}else if(k==='drive'){state.drive=id;renderScene();renderPanel()}else if(k==='interior'){state.interior=id;renderPanel()}updateStats()});
$('#panelBody').addEventListener('input',e=>{if(e.target.matches('.range')){const id=e.target.id.replace('Range','');state[id]=Number(e.target.value);const out=document.querySelector('#'+id+'Value');if(out)out.textContent=(state[id]>0?'+':'')+state[id]+(id==='ride'||id==='track'?' mm':' %');const v=$('#viewerCar');if(id==='ride')v.style.bottom=(28-state.ride*.5)+'px'; if(id==='track')v.style.left='50%'; updateStats()}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const view=b.dataset.view;$('#viewerCar').style.filter=view==='interior'?'brightness(.72) contrast(1.1)':'none';$('#viewerCar').style.transform=view==='rear'?'translate(-50%,-40%) scaleX(-1)':view==='side'?'translate(-50%,-42%) scaleX(1.03)':'translate(-50%,-42%)'}));
$('#saveBuildBtn').addEventListener('click',()=>{const c=car();const blob=new Blob([JSON.stringify({...state,vehicle:c.name},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='driveforge-build.json';a.click();URL.revokeObjectURL(a.href);toast('Build saved')});
$('#premiumBtn').addEventListener('click',()=>$('#premiumModal').classList.remove('hidden'));$('#closePremium').addEventListener('click',()=>$('#premiumModal').classList.add('hidden'));$('#unlockPremium').addEventListener('click',()=>{state.pro=true;$('#premiumModal').classList.add('hidden');$('#premiumBtn').textContent='♛ Pro Garage · UNLOCKED';renderPanel();toast('Pro Garage unlocked — demo only')});
function start(mode){$('#modeScreen').classList.add('hidden');if(mode==='scratch'){state.car='lamborghini-revuelto';state.paint='#9a5c09';state.body='wide';state.engine='v12';state.pro=true;state.tab='body'}else{state.car='bmw-m3';state.paint=car().color;state.engine='stock';state.body='stock';state.tab='vehicle'}showStudio()}
document.querySelectorAll('[data-start-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.startMode)));
$('#heroBuild').addEventListener('click',()=>$('#modeScreen').classList.remove('hidden'));$('#heroGarage').addEventListener('click',()=>document.querySelector('#garageSection').scrollIntoView({behavior:'smooth'}));document.querySelector('[data-garage]').addEventListener('click',()=>document.querySelector('#garageSection')?.scrollIntoView({behavior:'smooth'}));document.querySelector('[data-home]').addEventListener('click',showHome);document.querySelector('[data-build]').addEventListener('click',()=>$('#modeScreen').classList.remove('hidden'));document.querySelector('[data-catalog]').addEventListener('click',()=>document.querySelector('#garageSection').scrollIntoView({behavior:'smooth'}));$('#savedBtn').addEventListener('click',()=>toast('Saved builds are stored as JSON from the Build screen'));
renderBrands();renderGarage();
